name: CI

on:
  push:
  pull_request:

jobs:
  cargo:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        working-directory: src-tauri/
        run: cargo build --locked --release
      - name: Format check
        working-directory: src-tauri/
        run: cargo fmt --check
      - name: Clippy
        working-directory: src-tauri/
        run: cargo clippy -- --deny warnings
      - name: Test
        working-directory: src-tauri/
        run: cargo test --all-targets --all-features
      - name: Audit
        working-directory: src-tauri/
        run: cargo audit

  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Build
        run: npx run build
      - name: ESLint
        run: npx eslint
      - name: Prettier
        run: npx prettier --check .

  build:
    runs-on: windows-latest
    needs:
      - cargo
      - npm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Tauri build
        run: npx tauri build
